### ISSUE TITLE
Shooting a portal over the exit causes the exit to disappear

### ISSUE THREAD

**Issue by realityfabric** [JonathanNiehenke/JS_Portal#2]
Shooting a portal onto the tile which has the Exit is successful, and when the portal is placed onto a different tile the Exit does not reappear.

Discovered on the first map of PortalLevels.txt on commit 781e3cea45192f12f04c80ba70792747115d3442.

Tested in Firefox on Ubuntu 16.04.

**Comment by JonathanNiehenke** [comment]
Fixed in commit 04f094a7208ae1c9d7a2fe2483eaf87851ea651a.
Explanation: So when a portal is removed (rather appearing somewhere else) it is always replaced with a wall.
Cause: Portal should not appear on exit and therefore eventually replace it with a wall.
Solution: Include condition stopping the current path of the portal's shell on Exit or other open portal tiles.
